version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gustavomachado
      POSTGRES_PASSWORD: 243677
      POSTGRES_DB: rndr_token_predict
    ports:
      - "5434:5432"
