services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres23
      POSTGRES_DB: crypto_model_db
    ports:
      - "5434:5432"
    networks:
      - app-tier

  frontend:
    build: ./frontend
    image: src/frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - app-tier

  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://gustavomachado:newpassword@postgres:5432/rndr_token_predict"
      TF_ENABLE_ONEDNN_OPTS: 0
    ports:
      - "5433:5432"
    depends_on:
      - postgres
    container_name: backend
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge